name: RedRover Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read file
        id: file
        run: echo "::set-output name=content::$(cat red_rover/custom_prompt.txt)"
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.BANKRATE_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          poem_enabled: true
          less_verbose_review: false
          review_comment_lgtm: false
          openai_heavy_model: gpt-4
          path_filters: |
            !dist/**
            !**/*.lock
          system_message: ${{ steps.file.outputs.content }}   
